// tslint:disable
/**
 * Model Editor API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DefaultApi } from './api'
import { Configuration, ConfigurationParameters } from './configuration'
import * as url from "url"

// monkey patch URLSearchParams until this issue is resolved: https://github.com/swagger-api/swagger-codegen/issues/6403
// @ts-ignore
url.URLSearchParams = URLSearchParams;

const API_CONFIG: ConfigurationParameters = {
    basePath: 'http://localhost:8081/meditor/api',
}

const mEditorAPI = new DefaultApi(new Configuration(API_CONFIG))

export default mEditorAPI
