version: "3.3"

services:
  notebookviewer:
    container_name: meditor_notebookviewer
    build: packages/notebook-viewer
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - ./packages/notebook-viewer:/usr/src/app

  proxy:
    container_name: meditor_proxy
    build: packages/proxy
    restart: on-failure

  notifier:
    container_name: meditor_notifier
    build: packages/notifier
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./packages/notifier:/usr/src/app
      - /usr/src/app/node_modules

  app:
    container_name: meditor_app
    build: packages/app
    env_file:
      - .env
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./packages/app:/usr/src/app
      - /usr/src/app/node_modules

  docs:
    container_name: meditor_docs
    build: packages/docs
    env_file:
      - .env
    ports:
      - "127.0.0.1:3030:3030"

  legacy-api:
    container_name: meditor_legacy-api
    build: packages/legacy-api
    restart: always
    env_file:
      - .env
    volumes:
      - ./packages/legacy-api:/usr/src/app
      - /usr/src/app/node_modules

  database:
    container_name: meditor_database
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "127.0.0.1:27018:27017"

  nats:
    container_name: meditor_nats
    volumes:
      - ./nats-data:/nats/data
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"

  monitor:
    container_name: meditor_monitor

  agent:
    container_name: meditor_agent
