/**
 * Model Editor API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelXmeditor {
    /**
     * Name of the field in the model to be used as a title
     */
    title?: string;
    /**
     * Date when a last document edit was made
     */
    modifiedOn?: string;
    /**
     * Author who last modified a document belonging to the model
     */
    modifiedBy?: string;
    /**
     * Number of documents belonging to the model
     */
    count?: string;
}
