/**
 * Model Editor API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocumentXmeditor {
    /**
     * JSON path to the field in the Model to be used as title in displays
     */
    title?: string;
    /**
     * Date-time of modification
     */
    modifiedOn?: string;
    /**
     * Modifier's user name
     */
    modifiedBy?: string;
}
