/**
 * Model Editor API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Icon for the model: currently limited to Font Awesome
 */
export interface ModelIcon {
    /**
     * Name of the Font Awesome icon (ex: )
     */
    name?: string;
    /**
     * Background color to be used for the Font Awesome icon (ex: )
     */
    color?: string;
}
