name: Build

# This action works with pull requests and pushes to branches other than main
on:
  push:
    #branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        directory:
          [
            "packages/app",
            "packages/docs",
            "packages/legacy-api",
            "packages/notebook-viewer",
            "packages/notifier",
            "packages/proxy",
          ]

    steps:
      - name: Checkout latest code from branch
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # Fetch only the changes to the previous commit
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: packages/app/package-lock.json

      - name: Version Check
        uses: EndBug/version-check@v2.1.3
        with:
          diff-search: true

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
