name: Continuous Integration

# This action works with pull requests and pushes to branches other than main
on:
  pull_request:

jobs:
  app-jest:
    runs-on: ubuntu-latest
    name: app-node-${{ matrix.node }}
    strategy:
      matrix:
        node: [16] # One or more Node versions to test against
      fail-fast: true

    steps:
      - name: Checkout latest code from branch
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # Fetch only the changes to the previous commit
          fetch-depth: 0

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: packages/app/package-lock.json

      - name: Install package dependencies
        working-directory: packages/app
        run: npm install

      - name: Run tests
        working-directory: packages/app
        run: npm run test
